name: Build Action

on:
  push:
    branches:
      - '*'
      - '!v*'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build